image: node

before_script:
  - cd app/
  - npm install

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm run build
    - npm run generate
    - mv dist ../piblic
  artifacts:
    paths:
      - public
  only:
    - master
